name: alloy-client

configs:
  client_all_alloy:
    file: "./configs/client-all.alloy"

services:
  alloy-client:
    image: grafana/alloy:latest
    hostname: alloy-client
    expose:
      - 4317 #otlp-gprc
      - 4318 #otlp-http
    command: |
      run 
      --server.http.listen-addr=0.0.0.0:12345
      --stability.level=public-preview
      --storage.path=/var/lib/alloy/data
      /etc/alloy/all.alloy
    ports:
      - '127.0.0.1:4318:4318'
      - '127.0.0.1:4317:4317'
    networks:
      docker-net:
      grafana-net:
    environment:
      - HOSTNAME=alloy-srv
    configs:
      - source: client_all_alloy
        target: /etc/alloy/all.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.http.services.alloy-client-ui-svc.loadbalancer.server.port: 12345
      traefik.http.routers.alloy-client-ui-rtr.entrypoints: web,websecure
      traefik.http.routers.alloy-client-ui-rtr.rule: Host(`alloy-client-ui.localhost`)
      traefik.http.routers.alloy-client-ui-rtr.tls: true
      traefik.http.routers.alloy-client-ui-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.alloy-client-ui-rtr.service: alloy-client-ui-svc

networks:
  docker-net:
    external: true
  grafana-net:
    external: true

volumes:
  alloy-vol:
    name: alloy-vol
