networks:
  dockernet:
    external:
      true
services:
    
  mongodb.db:
      image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-5.0}
      restart: unless-stopped
      container_name: mongodb.db
      networks:
        - dockernet
      ports:
        - 27018:27017
      # volumes:
      #   - mongodb_data:/bitnami/mongodb
      environment:
        - MONGODB_ENABLE_JOURNAL=false
        - ALLOW_EMPTY_PASSWORD=no
        - MONGODB_ROOT_USER=root-admin
        - MONGODB_ROOT_PASSWORD=root-password
        - MONGODB_USERNAME=username
        - MONGODB_PASSWORD=password
