networks:
  dockernet:
    external: true

services:
  traefikproxy:
    image: traefik:v3.3
    container_name: traefikproxy
    restart: unless-stopped
    command:
        # Globals 
      - '--global.checknewversion=true'
      - '--global.sendanonymoususage=false'
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--log.format=common' #common|json
      - '--accesslog.filepath=/var/lib/traefik/traefik.log'
      - '--accesslog.format=json'
        # entrypoints
      - '--entryPoints.http.address=:80'
      - '--entryPoints.https.address=:443'
      - '--entryPoints.http.http.redirections.entryPoint.to=https'
      - '--entryPoints.http.http.redirections.entryPoint.scheme=https'
        # Providers
      - '--providers.docker.endpoint=unix://var/run/docker.sock'
      - '--providers.docker.exposedbydefault=false'
        # Prod certs resolvers
      - '--certificatesResolvers.letsencrypt.acme.email=email@gmail.com'
      - '--certificatesResolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.letsencrypt.acme.storage=acme.json'
      - '--certificatesResolvers.letsencrypt.acme.httpChallenge.entrypoint=http'
      - '--certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare'
        # Dev certs resolvers
      - '--certificatesResolvers.dev-letsencrypt.acme.email=email@gmail.com'
      - '--certificatesResolvers.dev-letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.dev-letsencrypt.acme.storage=acme.json'
      - '--certificatesResolvers.dev-letsencrypt.acme.httpChallenge.entrypoint=http'
    networks:
      - dockernet
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/var/lib/traefik/acme.json:rw
    environment:
      - DOMAIN01=${DOMAIN01:-domain.dev}
      - SUBDOMAIN01=${SUBDOMAIN01:-sub.domain.dev}
      # - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:-000000000aaaaaaaaa}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entrypoints=http,https
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN01}`)
      - traefik.http.routers.traefik-rtr.tls=true
      - traefik.http.routers.traefik-rtr.tls.certresolver=dev-letsencrypt
      - traefik.http.routers.traefik-rtr.tls.domains[0].main=${DOMAIN01}
      - traefik.http.routers.traefik-rtr.tls.domains[0].sans=${SUBDOMAIN01}
      - traefik.http.services.traefik-svc.loadbalancer.server.port=8080
# Add .env file & put DOMAINS in
# DOMAIN01=
# SUBDOMAIN01=
