networks:
  dockernet:
    external: true
  redisnet: {}

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: |
      redis-server --save 60 1 --loglevel warning
    deploy:
      resources:
        limits:
          memory: 200Mb
          cpus: 0.2
    networks:
      - redisnet

  redisinsight:
    image: redis/redisinsight:2.66
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200Mb
          cpus: 0.2
    networks:
      - dockernet
      - redisnet
    ports:
      - 5540:5540
    # volume:
    #   - redisinsight:/data
