networks:
  dockernet:
    external: true

volumes:
  authentik-db-vol:
    name: authentik-db-vol
    # driver: local
    # driver_opts:
    #   type: nfs4
    #   o: "addr=127.0.0.1,rw"
    #   device: ":/mnt/storage/authentik/db"
  authentik-redis-vol:
    name: authentik-redis-vol
    # driver: local
    # driver_opts:
    #   type: nfs4
    #   o: "addr=127.0.0.1,rw"
    #   device: ":/mnt/storage/authentik/redis"

services:
  authentik-db:
    image: postgres:17-alpine
    restart: unless-stopped
    networks:
      - dockernet
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - authentik-db-vol:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${PG_PASS:-authentik}
      - POSTGRES_USER=${PG_USER:-authentik}
      - POSTGRES_DB=${PG_DB:-authentik}

  authentik-redis:
    image: redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - dockernet
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - authentik-redis-vol:/data

  authentik-server:
    image: ghcr.io/goauthentik/server:2025.2.1
    restart: unless-stopped
    networks:
      - dockernet
    command: server
    environment:
      - AUTHENTIK_REDIS__HOST=authentik-redis
      - AUTHENTIK_POSTGRESQL__HOST=authentik-db
      - AUTHENTIK_POSTGRESQL__USER=${PG_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${PG_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_PASS:-authentik}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=${AUTHENTIK_ERROR_REPORTING__ENABLED:-true}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY:-V4PeA5cu9dKFiZMt8rYgVBZ5wIcXpRktO00erN0Qx91O8TCiYxQ0ZthfvdSaESmRmoyrVaseadyKnOzJ}
    volumes:
      - ./media:/media
      - ./templates:/templates
    depends_on:
      - authentik-db
      - authentik-redis
    labels:
      - traefik.enable=true
      # - (routers)
      - traefik.http.routers.authentik-rtr.entrypoints=http,https
      - traefik.http.routers.authentik-rtr.rule=Host(`authentik.domain.com`)
      - traefik.http.routers.authentik-rtr.tls=true
      - traefik.http.routers.authentik-rtr.tls.certresolver=cloudflare
      # - (service)
      - traefik.http.routers.authentik-rtr.service=authentik-svc
      - traefik.http.services.authentik-svc.loadbalancer.server.port=9000

  authentik-worker:
    image: ghcr.io/goauthentik/server:2025.2.4
    restart: unless-stopped
    command: worker
    deploy:
      replicas: 2
      
    networks:
      - dockernet
    environment:
      - AUTHENTIK_REDIS__HOST=authentik-redis
      - AUTHENTIK_POSTGRESQL__HOST=authentik-db
      - AUTHENTIK_POSTGRESQL__USER=${PG_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${PG_DB}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_PASS}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY:-V4PeA5cu9dKFiZMt8rYgVBZ5wIcXpRktO00erN0Qx91O8TCiYxQ0ZthfvdSaESmRmoyrVaseadyKnOzJ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./templates:/templates
    depends_on:
      - authentik-db
      - authentik-redis
