# docker run -i -t --rm ghcr.io/steveiliop56/tinyauth:v5 user create --interactive

name: tinyauth
services:
  tinyauth:
    image: ghcr.io/tinyauthapp/tinyauth:nightly
    restart: unless-stopped
    networks:
      docker-net:
    deploy:
      resources:
        reservations:
          cpus: "0.3"
          memory: "400MiB"
        limits:
          memory: "500MiB"
          cpus: "0.5"
    secrets:
      - users
    environment:
      TINYAUTH_APPURL: https://tinyauth.localhost
      TINYAUTH_AUTH_USERSFILE: "/run/secrets/users"
      TINYAUTH_LOG_JSON: true
      TINYAUTH_LOG_STREAMS_AUDIT_ENABLED: true
      TINYAUTH_AUTH_SECURECOOKIE: true
      TINYAUTH_UI_TITLE: tinyauth-app

      # TINYAUTH_UI_FORGOTPASSWORDMESSAGE: 
      # TINYAUTH_UI_BACKGROUNDIMAGE: 
        
      # TINYAUTH_LDAP_ADDRESS: ldap://my-lldap-server:3890
      # TINYAUTH_LDAP_BINDDN: uid=tinyauth,ou=people,dc=lldalp,dc=localhost
      # TINYAUTH_LDAP_BINDPASSWORD: tinyauth-password
      # TINYAUTH_LDAP_BASEDN: dc=lldalp,dc=localhost
      # TINYAUTH_LDAP_INSECURE: true
      # TINYAUTH_LDAP_SEARCHFILTER: "(uid=%s)"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tinyauth-vol:/data:rw
    labels:
      traefik.enable: true
      traefik.http.middlewares.tinyauth-mdl.forwardauth.address: http://tinyauth:3000/api/auth/traefik
      traefik.http.services.tinyauth-svc.loadbalancer.server.port: 3000
      traefik.http.routers.tinyauth-rtr.entrypoints: websecure
      traefik.http.routers.tinyauth-rtr.rule: Host(`tinyauth.localhost`)
      traefik.http.routers.tinyauth-rtr.tls: true
      traefik.http.routers.tinyauth-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.tinyauth-rtr.service: tinyauth-svc
      tinyauth.apps.appname.loadbalancer.groups: admins,monitoring

secrets:
  users:
    file: '${PWD}/secrets/users'


networks:
  docker-net:
    external: true

volumes:
  tinyauth-vol:
    name: tinyauth-vol