name: redis




services:
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    deploy:
      resources:
        limits:
          memory: "200MiB"
          cpus: "0.2"
    networks:
      redis-net:

  redisinsight:
    image: redis/redisinsight:2.66
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "200MiB"
          cpus: "0.2"
    networks:
      docker-net:
      redis-net:
    ports:
      - 5540:5540
    volumes:
      - redisinsight-vol:/data

networks:
  docker-net:
    external: true
  redis-net: {}

volumes:
  redisinsight-vol:
    name: redisinsight-vol
    driver: local