networks:
  dockernet:
    external: true

volumes:
  portainer-storage:
    name: portainer-storage

services:
  portainer:
    image: portainer/portainer-ce:sts
    restart: unless-stopped
    networks:
      - dockernet
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-storage:/data:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-rtr.entrypoints=http,https
      - traefik.http.routers.portainer-rtr.tls=true
      - traefik.http.routers.portainer-rtr.tls.certresolver=dev-letsencrypt
      - traefik.http.routers.portainer-rtr.rule=Host(`portainer.local.kvruntime.com`)
      - traefik.http.services.portainer-svc.loadbalancer.server.port=9000
