name: traefik-dev

services:
  traefik:
    image: traefik:v3.7.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: "200Mib"
          cpus: "0.25"
        limits:
          memory: "400Mib"
          cpus: "0.5"
    command:
      - --global.checknewversion=true
      - --global.sendanonymoususage=false
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --ping=true
      - --ping.entryPoint=web

      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443

      - --providers.docker.endpoint=unix://var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=docker-net
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true

      - --certificatesResolvers.letsencrypt.acme.email=admin@local.host
      - --certificatesResolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.letsencrypt.acme.storage=/var/traefik/certs/letsencrypt-acme.json
      - --certificatesResolvers.letsencrypt.acme.httpChallenge.entrypoint=web

      - --log.level=INFO # TRACE - INFO - DEBUG - WARN - ERROR - FATAL - PANIC
      - --log.format=json
      - --log.nocolor=false
      - --log.compress=true
      - --log.filepath=/var/log/traefik/traefik.log

      - --accessLog=true
      - --accesslog.format=json
      - --accessLog.addinternals=true
      - --accesslog.filepath=/var/log/traefik/access.log

      - --experimental.fastProxy
      - --experimental.otlpLogs=true
    networks:
      docker-net:
    ports:
      - "80:80"
      - "443:443"
      # - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./data/certs:/var/traefik/certs:rw
      - ./data/logs:/var/log/traefik/:rw
      - ./configs/dynamic:/etc/traefik/dynamic:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-rtr.service: "api@internal"
      traefik.http.routers.traefik-rtr.entrypoints: web,websecure
      traefik.http.routers.traefik-rtr.rule: "Host(`traefik.localhost`)"
      traefik.http.routers.traefik-rtr.tls: "true"
      traefik.http.routers.traefik-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.traefik-rtr.tls.domains[0].main: "localhost"
      traefik.http.routers.traefik-rtr.tls.domains[0].sans: "*.localhost"

networks:
  docker-net:
    external: true
