name: traefik-http

configs:
  traefik_dynamic_yml:
    file: "./config/dynamic.yaml"

services:
  traefik:
    image: traefik:v3.7.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: "300MiB"
          cpus: "0.3"
        limits:
          memory: "400MiB"
          cpus: "0.5"
    command:
      - --global.checknewversion=true
      - --global.sendanonymoususage=false
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --ping=true
      - --ping.entryPoint=web

      - --entryPoints.web.address=:80

      - --providers.docker.endpoint=unix://var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=docker-net
      - --providers.file.filename=/etc/traefik/dynamic.yaml
      - --providers.file.watch=true

      - --log.level=INFO
      - --log.format=json
      - --log.nocolor=false
      - --log.compress=true
      - --log.filepath=/var/log/traefik/traefik.log

      - --accessLog=true
      - --accesslog.format=json
      - --accessLog.addinternals=true
      - --accesslog.filepath=/var/log/traefik/access.log

      - --experimental.fastProxy
      - --experimental.otlpLogs=true
    configs:
      - source: traefik_dynamic_yml
        target: /etc/traefik/dynamic.yaml
    networks:
      docker-net:
    ports:
      - '80:80'
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/logs:/var/log/traefik/:rw
    environment:
      TZ: UTF
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-rtr.service: "api@internal"
      traefik.http.routers.traefik-rtr.entrypoints: web
      traefik.http.routers.traefik-rtr.rule: "Host(`traefik.localhost`)"

networks:
  docker-net:
    external: true
