networks:
  dockernet:
    external: true

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    # volumes:
    #   - certs:/usr/share/elasticsearch/config/certs
    #   - esdata01:/usr/share/elasticsearch/data
    networks:
      - dockernet
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME:-elasticsearch}
      # - cluster.initial_master_nodes=es01,es02,es03
      # - discovery.seed_hosts=es02,es03
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-your_password}
      # - ES_PORT=127.0.0.1:9200
      # - bootstrap.memory_lock=true
      # - xpack.security.enabled=true
      # - xpack.security.http.ssl.enabled=true
      # - xpack.security.http.ssl.key=certs/es01/es01.key
      # - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      # - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.transport.ssl.key=certs/es01/es01.key
      # - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      # - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      # - xpack.security.transport.ssl.verification_mode=certificate
      # - xpack.license.self_generated.type=${LICENSE}
      - xpack.ml.use_auto_machine_memory_percent=true
      # - xpack.ml.use_auto_machine_memory_percent=true
      # - ENROLLMENT_TOKEN="token"
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl http://localhost:9200 | grep -q 'missing authentication credentials'",
    #     ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 120

  kibana:
    depends_on:
      - elasticsearch
        # condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.17.0
    # volumes:
      # - certs:/usr/share/kibana/config/certs
      # - kibanadata:/usr/share/kibana/data
    networks:
      - dockernet
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      # - ELASTICSEARCH_HOSTS=http://elasticsearch:9200,
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD:-your_password!}
      # - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
    #     ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 120


# /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic
# /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana