networks:
  dockernet:
    external: true

services:
  traefikproxy:
    image: traefik:3.3.0-rc2
    container_name: traefikproxy
    restart: unless-stopped
    command:
      - '--global.checknewversion=true'
      - '--global.sendanonymoususage=false'
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--log.format=common' #common|json
      - '--accesslog.filepath=/var/lib/traefik/traefik.log'
      - '--accesslog.format=json'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.https.address=:443'
      - '--providers.docker.endpoint=unix://var/run/docker.sock'
      - '--providers.docker.exposedbydefault=false'
      - '--certificateresolvers.letsencrypt.acme.email=victorespoir.dev@gmail.com'
      - '--certificateresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory'
      - '--certificateresolvers.letsencrypt.acme.storage=/var/lib/traefik'
      - '--certificateresolvers.letsencrypt.acme.httpchallenge.entrypoints=http'
      - '--certificateresolvers.staging-letsencrypt.acme.email=victorespoir.dev@gmail.com'
      - '--certificateresolvers.staging-letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificateresolvers.staging-letsencrypt.acme.storage=/var/lib/traefik'
      - '--certificateresolvers.staging-letsencrypt.acme.httpchallenge.entrypoints=http'
    networks:
      - dockernet
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/var/lib/traefik/acme.json:rw
    environment:
      - DOMAIN01=${DOMAIN01:-victor3spoir.com}
      - SUBDOMAIN01=${SUBDOMAIN01:-local.victor3spoir.com}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entrypoints=http,https
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN01}`)
      - traefik.http.routers.traefik-rtr.tls=true
      - traefik.http.routers.traefik-rtr.tls.certresolver=dev-letsencrypt
      - traefik.http.routers.traefik-rtr.tls.domains[0].main=${DOMAIN01}
      - traefik.http.routers.traefik-rtr.tls.domains[0].sans=${SUBDOMAIN01}
      - traefik.http.services.traefik-svc.loadbalancer.server.port=8080

