networks:
  dockernet:
    external: true

volumes:
  minio-vol:
    name: minio-vol
    driver: local
    driver_opts:
      type: nfs4
      o: addr=0.0.0.0,rw,nolock,hard,nointr,nfsvers=4.1
      device: :/mnt/storage/minio

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    restart: unless-stopped
    command: server /data --address ":9000" --console-address ":9001"
    networks:
      - dockernet
    ports:
      - 9000:9000 # api
      - 9001:9001 # webui
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL:-http://localhost:9000}
      # - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-access_key"}
      # - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-secret_key"}
      # - MINIO_KMS_SECRET_KEY=${MINIO_KMS_SECRET_KEY:-kms_master_key"}
      # - MINIO_UPDATE_MINISIGN_PUBKEY=${MINIO_UPDATE_MINISIGN_PUBKEY:-RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav"}
      # - MINIO_CONFIG_ENV=${MINIO_CONFIG_ENV:-config.env"}
    volumes:
      - minio-vol:/data:rw
    labels:
      - traefik.enable=true
        # services
      - traefik.http.services.minio.loadbalancer.server.port=9000
        # routes
      - traefik.http.routers.minio.entrypoints=http,https
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.certresolver=letsencrypt
      - traefik.http.routers.minio.rule=Host(`minio.<domain.com>`)
  minio-client:
    image: minio/mc
    networks:
      - dockernet
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc --help
      "
