networks:
  dockernet:
    external: true

services:
  inbucket:
    image: inbucket/inbucket:main
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200Mib
          cpus: 0.2
    networks:
      - dockernet
    ports:
      # - 1100:1100 # pop3
      # - 2500:2500 # smtp
      - 49000:9000 # http webui
