discovery:
  instrument:
    - open_ports: 443
log_level: DEBUG
ebpf:
  wakeup_len: 100
otel_metrics_export:
  endpoint: http://alloy:4318
otel_traces_export:
  endpoint: http://alloy:4318
prometheus_export:
  port: 8999
  path: /metrics
internal_metrics:
  exporter: prometheus
  prometheus:
    port: 6060
    exporter: prometheus # otel
    path: /internal/metrics