image:
  registry: docker.io
  repository: traefik
  tag: v3.3
  pullPolicy: IfNotPresent

additionalArguments:
  - --providers.kubernetesingress.ingressclass=traefik-internal
  - --log.level=DEBUG
  - --global.checknewversion=true
  - --global.sendanonymoususage=false
  - --log.level=DEBUG
  - --api.insecure=true
  - --log.format=common #common|json
    # entrypoints
  - --entryPoints.http.address=:80
  - --entryPoints.https.address=:443
  - --entryPoints.http.http.redirections.entryPoint.to=https
  - --entryPoints.http.http.redirections.entryPoint.scheme=https
  # Providers
  - --providers.kubernetesingress=true
    # http challenge
  - --certificatesResolvers.letsencrypt.acme.email=user@domain.com
  - --certificatesResolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
  - --certificatesResolvers.letsencrypt.acme.storage=/var/traefik/certs/letsencrypt-acme.json
  - --certificatesResolvers.letsencrypt.acme.httpChallenge.entrypoint=http
  # dns challenge
  # - --certificatesResolvers.cloudflare.acme.email=user@domain.com
  # - --certificatesResolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
  # - --certificatesResolvers.cloudflare.acme.storage=/var/traefik/certs/cloudflare-acme.json
  # - --certificatesResolvers.cloudflare.acme.keyType=EC256
  # - --certificatesResolvers.cloudflare.acme.dnsChallenge.provider=cloudflare
  # - --certificatesResolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53

ports:
  traefik:
    port: 8080
  web:
    port: 80
    redirections:
      to: https
      scheme: https
      permanent: true
  websecure:
    port: 443
    tls:
      enable: true
      certResolver: letsencrypt

persistence:
  enabled: true
  name: traefik-volume
  size: 100Mi
  path: /var/traefik/certs

# deployment:
#   initContainers:
#     - name: volume-permissions
#       image: busybox
#       command: ["sh", "-c", "chmod -Rv 600 /var/traefik/certs/*"]
#       volumeMounts:
#         - name: traefik-volume
#           mountPath: /var/traefik/certs

ingressRoute:
  dashboard:
    enabled: false

ingressClass:
  enabled: true
  isDefaultClass: true

