http_server {
        enable = true
        port = 8081
        parallel = 2
        username = admin
        password = public
        auth_type = basic
        jwt {
                public.keyfile = "/etc/certs/jwt/jwtRS256.key.pub"
                private.keyfile = "/etc/certs/jwt/jwtRS256.key"
        }
}