networks:
  dockernet:
    external: true

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    ports:
      - 5000:80
    networks:
      - dockernet
    labels:
      - traefik.enable=true
    logging:
      driver: gelf
      options:
        gelf-address: UDP://elasticsearch:12201
        tag: excalidraw
      
