name: loki-dev



services:
  loki:
    image: grafana/loki:3.1.2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500Mib
          cpus: 0.5
    command:
      - -config.file=/etc/loki/loki.yaml
      - -config.expand-env=true
    networks:
      docker-net:
      grafana-net:
    volumes:
      - loki-vol:/loki
      # - ./rules:/loki/rules
    configs:
      - source: loki_yaml
        target: /etc/loki/loki.yaml
    labels:
      traefik.enable: true
      traefik.http.services.loki-dev-svc.loadbalancer.server.port: 3100
      traefik.http.routers.loki-dev-rtr.rule: Host(`loki-dev.localhost`)
      traefik.http.routers.loki-dev-rtr.tls: true
      traefik.http.routers.loki-dev-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.loki-dev-rtr.service: loki-dev-svc
    healthcheck:
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  loki-vol:
    name: loki-vol
  

configs:
  loki_yaml:
    file: "./configs/loki.yaml"

networks:
  docker-net:
    external: true
  grafana-net:
    external: true
