name: loki-dev

configs:
  loki_yaml:
    file: "./configs/loki.yaml"

services:
  loki:
    image: grafana/loki:main
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500Mib
          cpus: 0.5
    command:
      - -config.file=/etc/loki/loki.yaml
      - -config.expand-env=true
    networks:
      docker-net:
    configs:
      - source: loki_yaml
        target: /etc/loki/loki.yaml
    labels:
      traefik.enable: true
      traefik.http.services.loki-dev-svc.loadbalancer.server.port: 3100
      traefik.http.routers.loki-dev-rtr.rule: Host(`loki-dev.localhost`)
      traefik.http.routers.loki-dev-rtr.tls: true
      traefik.http.routers.loki-dev-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.loki-dev-rtr.service: loki-dev-svc

networks:
  docker-net:
    external: true
