listen_addresses = '*'
port = 5432
max_connections = 100

shared_buffers = 256MB
work_mem = 16MB
maintenance_work_mem = 128MB
effective_cache_size = 512MB



autovacuum = on


wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
wal_keep_size = 2GB
wal_compression = on

checkpoint_timeout = 15min
checkpoint_completion_target = 0.9
max_wal_size = 2GB
min_wal_size = 512MB

hot_standby = on
synchronous_commit = on


log_destination = 'stderr'
logging_collector = off
log_timezone = 'UTC'
timezone = 'UTC'

datestyle = 'iso, mdy'
timezone = 'UTC'
lc_messages = 'C'
lc_monetary = 'C'
lc_numeric = 'C'
lc_time = 'C'
default_text_search_config = 'pg_catalog.english'