apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-demo
  namespace: demo
  labels:
    app: deploy-demo-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-webapp
  template:
    metadata:
      name: demo
      labels:
        app: demo-webapp
    spec:
      containers:
        - name: demo-webapp
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-webapp-svc
  namespace: demo
spec:
  selector:
    app: deploy-demo-webapp
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30001
