apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: webapps
spec:
  containers:
  - name: nginx-pod
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
