apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-demo
  namespace: demo
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    # name: php-redis
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3