apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-guestbook
  namespace: demo
  labels:
    app: rs-guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
---
# The service
apiVersion: v1
kind: Service
metadata:
  name: rs-guestbook-svc
  namespace: demo
spec:
  selector:
    app: rs-guestbook
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80