listen_addresses = '*'
port = 5432
max_connections = 100

shared_buffers = 1GB
effective_cache_size = 3GB
maintenance_work_mem = 256MB
work_mem = 8MB

shared_preload_libraries = 'timescaledb'

log_destination = 'stderr'
logging_collector = off

# Write-Ahead Log
wal_level = replica
wal_compression = on
max_wal_senders = 10
wal_keep_size = 1GB
max_wal_size = 4GB
min_wal_size = 1GB
wal_buffers = 16MB


timescaledb.max_background_workers = 8
max_worker_processes = 16
max_parallel_workers = 8
max_parallel_workers_per_gather = 4

# Autovacuum settings
autovacuum = on

checkpoint_timeout = 15min
checkpoint_completion_target = 0.9

# archive_mode = on
# archive_command = 'pgbackrest --stanza=timescaledb archive-push %p'
archive_timeout = 300

datestyle = 'iso, mdy'
timezone = 'UTC'
lc_messages = 'C'
lc_monetary = 'C'
lc_numeric = 'C'
lc_time = 'C'
default_text_search_config = 'pg_catalog.english'