networks:
  dockernet:
    external: true

volumes:
  odoo_web_data:
    name: odoo_web_data
  odoo_db_data:
    name: odoo_db_data

secrets:
  db_user:
    file: ./db_user
  db_password:
    file: ./db_password

services:
  odoo_web:
    image: odoo:17
    restart: unless-stopped
    privileged: true
    depends_on:
      - odoo_db
    networks:
      - dockernet
    ports:
      - 28069:8069
    environment:
      - HOST=odoo_db
      - USER_FILE=/run/secrets/db_user
      - PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_user
      - db_password
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      # - odoo_web_data:/var/lib/odoo:rw
      # - odoo_web_data:/mnt/extra-addons:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.odoo-rtr.entrypoints=http,https
      - traefik.http.routers.odoo-rtr.rule=Host(`odoo.local.kvruntime.com`)
      - traefik.http.routers.odoo-rtr.tls=true
      - traefik.http.routers.odoo-rtr.tls.certresolver=dev-letsencrypt
      - traefik.http.routers.odoo-admin-rtr.entrypoints=http,https
      - traefik.http.routers.odoo-admin-rtr.rule=PathPrefix(`/web`)
      - traefik.http.services.odoo-svc.loadbalancer.server.port=8069

  odoo_db:
    image: postgres:16-alpine
    restart: unless-stopped
    privileged: true
    networks:
      - dockernet
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=postgres
    secrets:
      - db_user
      - db_password
    # volumes:
    #   - odoo_db_data:/var/lib/postgresql/data:rw
    labels:
      - traefik.enable=true
# default: admin : admin
