name: wordpress

services:
  wordpress-db:
    image: mysql:8.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    secrets:
      - mysql_password
      - mysql_root_password
    deploy:
      resources:
        reservations:
          memory: "300MiB"
          cpus: "0.1"
        limits:
          memory: "600MiB"
          cpus: "0.2"
    networks:
      wordpress-net:
    environment:
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD_FILE: "/run/secrets/mysql_password"
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql_root_password"
    volumes:
      - wordpress-db-vol:/var/lib/mysql

  wordpress-web:
    depends_on:
      - wordpress-db
    image: wordpress:6.8-apache
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    secrets:
      - mysql_password
      - mysql_root_password
    deploy:
      resources:
        reservations:
          memory: "200MiB"
          cpus: "0.1"
        limits:
          memory: "400MiB"
          cpus: "0.2"
    networks:
      wordpress-net:
      docker-net:
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD_FILE: "/run/secrets/mysql_password"
    volumes:
      - wordpress-web-vol:/var/www/html
    labels:
      traefik.enable: "true"
      traefik.http.services.wordpress-svc.loadbalancer.server.port: 80
      traefik.http.routers.wordpress-rtr.entrypoints: web,websecure
      traefik.http.routers.wordpress-rtr.rule: Host(`wordpress.localhost`)
      traefik.http.routers.wordpress-rtr.tls: true
      traefik.http.routers.wordpress-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.wordpress-rtr.service: wordpress-svc
      # traefik.http.routers.wordpress-rtr.middlewares: 

      traefik.http.routers.wordpress-auth-rtr.entrypoints: web,websecure
      traefik.http.routers.wordpress-auth-rtr.rule: Host(`wordpress.localhost`) && (PathPrefix(`/wp-login`) || PathPrefix(`/wp-admin`))
      traefik.http.routers.wordpress-auth-rtr.tls: true
      traefik.http.routers.wordpress-auth-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.wordpress-auth-rtr.service: wordpress-svc
      # traefik.http.routers.wordpress-auth-rtr.middlewares:


secrets:
  mysql_password:
    file: "./secrets/mysql_password"
  mysql_root_password:
    file: "./secrets/mysql_root_password"

networks:
  docker-net:
    external: true
  wordpress-net: {}

volumes:
  wordpress-db-vol:
    name: wordpress-db-vol
    driver: local
  wordpress-web-vol:
    name: wordpress-web-vol
    driver: local
