name: pgsql

networks:
  docker-net:
    external: true

volumes:
  pgsql-vol:
    name: pgsql-vol
    driver: local


services:
  pgsql:
    image: postgres:17-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200Mb
          cpus: 0.2
    networks:
      - docker-net
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - pgsql-vol:/var/lib/postgresql/data


