name: pgsql


configs:
  postgres_config:
    content: |
      listen_addresses = '*'
      port = 5432
      max_connections = 100

      shared_buffers = 128MB
      work_mem = 4MB
      maintenance_work_mem = 64MB
      effective_cache_size = 512MB

      log_destination = 'stderr'
      logging_collector = on
      log_directory = 'log'
      log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
      log_truncate_on_rotation = on
      log_rotation_age = 1d
      log_rotation_size = 0
      log_statement = 'none'
      log_timezone = 'UTC'

      autovacuum = on

      wal_level = replica
      max_wal_senders = 10
      wal_keep_size = 1GB
      max_wal_size = 1GB
      min_wal_size = 80MB

      datestyle = 'iso, mdy'
      timezone = 'UTC'
      lc_messages = 'C'
      lc_monetary = 'C'
      lc_numeric = 'C'
      lc_time = 'C'
      default_text_search_config = 'pg_catalog.english'
  postgres_hba_config:
    content: |
      # TYPE  DATABASE        USER            ADDRESS                 METHOD
      # local   all           postgres                                scram-sha-256
      local   all             all                                     scram-sha-256

      host    all             all             127.0.0.1/32            scram-sha-256
      host    all             all             ::1/128                 scram-sha-256
      host    all             all             0.0.0.0/0               scram-sha-256



services:
  pgsql:
    image: postgres:18-alpine
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.2"
          memory: 200MiB
        limits:
          cpus: "0.4"
          memory: 400MiB
    command: |
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgsql-vol:/var/lib/postgresql
    networks:
      - db-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
    configs:
      - source: postgres_config
        target: /etc/postgresql/postgresql.conf
      - source: postgres_hba_config
        target: /etc/postgresql/pg_hba.conf
    labels:
      traefik.enable: "true"
      traefik.tcp.services.pgsql-svc.loadbalancer.server.port: "5432"
      traefik.tcp.routers.pgsql-rtr.entrypoints: "pgsql"
      traefik.tcp.routers.pgsql-rtr.rule: "HostSNI(`*`)"
      traefik.tcp.routers.pgsql-rtr.tls: "false"
      traefik.tcp.routers.pgsql-rtr.service: "pgsql-svc"
      # traefik.tcp.routers.timescaledb-rtr.tls.certresolver: "letsencrypt"
      # traefik.tcp.routers.timescaledb-rtr.tls.passthrough: true

networks:
  db-net:
    driver: bridge
    external: true

volumes:
  pgsql-vol:
    name: pgsql-vol