networks:
  dockernet:
    external: true

services:
  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    networks:
      - dockernet
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
