networks:
  dockernet:
    external: true

volumes:
  uptimekuma-vol:
    name: uptimekuma-vol
    driver: local
    # driver_opts:
    #   type: nfs4
    #   o: "addr=127.0.0.1,rw"
    #   device: ":/mnt/storage/updtimekuma"

services:
  updtimekuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    networks:
      - dockernet
    deploy:
      resources:
        limits:
          memory: 200Mib
          cpus: 0.2
    # ports:
    #   - 3001:3001
    volumes:
      - uptimekuma-vol:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.services.updtimekuma-svc.loadbalancer.server.port=9000
      - traefik.http.routers.updtimekuma-rtr.entrypoints=http,https
      - traefik.http.routers.updtimekuma-rtr.tls=true
      - traefik.http.routers.updtimekuma-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.updtimekuma-rtr.rule=Host(`updtimekuma.<domain.com>`)
      - traefik.http.routers.updtimekuma-rtr.service=updtimekuma-svc
