datasources:
  postgres:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://kestra-db:5432/kestra
    username: postgres
    password: Password123!

kestra:
  jdbc:
    queues:
    messageProtection:
      enabled: true
      limit: 1048576
  server:
    basicAuth:
      enabled: true
      username: admin@local.host
      password: Password123!
  url: https://kestra.localhost
  repository:
    type: postgres
  storage:
    type: minio
    minio:
      endpoint: http://kestra-minio
      port: 9000
      accessKey: admin
      secretKey: Password123!
      bucket: kestra
      region: us-east-1
  queue:
    type: postgres
  tasks:
    tmpDir:
      path: "/tmp/kestra-wd/tmp"
