# https://docs.checkmk.com/latest/en/
# cmkadmin : ${CMK_PASSWORD}
# {URL}/cmk/check_mk
name: checkmk
services:
  checkmk:
    image: checkmk/check-mk-community:2.5.0-latest
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    container_name: "monitoring"
    restart: unless-stopped
    networks:
      docker-net:
    deploy:
      resources:
        reservations:
          memory: "700MiB"
          cpus: "0.5"
        limits:
          memory: "1400MiB"
          cpus: "1"
    expose:
      - 5000 #ui
      - 8000 #agent tls
    environment:
      CMK_PASSWORD: ${CMK_PASSWORD}
      TZ: UTC
      CMK_SITE_ID: cmk
    volumes:
      - checkmk-vol:/omd/sites
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ports:
      # - 8000:8000
      - 35000:5000
    labels:
      traefik.enable: "true"
      traefik.http.services.checkmk-svc.loadbalancer.server.port: 5000
      traefik.http.services.checkmk-svc.loadbalancer.server.scheme: http
      traefik.http.routers.checkmk-rtr.entrypoints: websecure
      traefik.http.routers.checkmk-rtr.rule: Host(`checkmkui.localhost`)
      traefik.http.routers.checkmk-rtr.tls: true
      traefik.http.routers.checkmk-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.checkmk-rtr.service: checkmk-svc

volumes:
  checkmk-vol:
    name: checkmk-vol

networks:
  docker-net:
    external: true
