volumes:
  nextcloud-web-data:
    name: nextcloud-web-data
  nextcloud-db-data:
    name: nextcloud-db-data

networks:
  dockernet:
    external: true

services:
  nextcloud-db:
    image: postgres:17-alpine
    restart: unless-stopped
    cpus: .5
    networks:
      - dockernet
    # volumes:
    #   - nextcloud-db-data:/var/lib/postgresql/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nextcloud}
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}

  nextcloud-web:
    image: nextcloud:29-apache
    restart: unless-stopped
    cpus: .5
    networks:
      - dockernet
    ports:
      - 30879:80
    # volumes:
    #   - ./apps:/var/www/html/custom_apps
    #   - ./config:/var/www/html/config
      # - nextcloud-web-data:/var/www/html
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nextcloud}
      - POSTGRES_HOST=${POSTGRES_HOST:-nextcloud-db}
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-password}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-localhost.com local.host} # space-separated list of domains
      - SMTP_SECURE=${SMTP_SECURE:-tls} # ssl/tls
      - SMTP_HOST=${SMTP_HOST:-localhost}
      - SMTP_PORT=${SMTP_PORT:-0000}
      - SMTP_AUTHTYPE=${SMTP_AUTHTYPE:-LOGIN} # LOGIN/PLAIN
      - SMTP_NAME=${SMTP_NAME:-admin}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-password}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-noreply@localhost.com}
      - MAIL_DOMAIN=${MAIL_DOMAIN:-localhost.com}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-512M}
      - PHP_UPLOAD_LIMIT=${PHP_UPLOAD_LIMIT:-512M}
