volumes:
  nextcloud-web-data:
    name: nextcloud-web-data
  nextcloud-mariadb-data:
    name: nextcloud-mariadb-data

networks:
  dockernet:
    external: true

services:
  nextcloud-mariadb:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    cpus: .5
    networks:
      - dockernet
    # volumes:
    #   - nextcloud-mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}

  nextcloud-web:
    image: nextcloud:29-apache
    restart: unless-stopped
    cpus: .5
    networks:
      - dockernet
    ports:
      - 30879:80
    volumes:
      - ./apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      # - nextcloud-web-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nextcloud}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_HOST=${MYSQL_HOST:-nextcloud-mariadb}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-password}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-localhost.com local.host} # space-separated list of domains
      - SMTP_SECURE=${SMTP_SECURE:-tls} # ssl/tls
      - SMTP_HOST=${SMTP_HOST:-localhost}
      - SMTP_PORT=${SMTP_PORT:-0000}
      - SMTP_AUTHTYPE=${SMTP_AUTHTYPE:-LOGIN} # LOGIN/PLAIN
      - SMTP_NAME=${SMTP_NAME:-admin-name}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-password}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-noreply@localhost.com}
      - MAIL_DOMAIN=${MAIL_DOMAIN:-localhost.com}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-512M}
      - PHP_UPLOAD_LIMIT=${PHP_UPLOAD_LIMIT:-512M}
