services:
  seaweed-master:
    image: chrislusf/seaweedfs:latest
    command: >
      master
      -ip=seaweed-master
      -ip.bind=0.0.0.0
    ports:
      - "9333:9333"
    volumes:
      - seaweed-master:/data

  seaweed-volume:
    image: chrislusf/seaweedfs:latest
    command: >
      volume
      -mserver=seaweed-master:9333
      -ip=seaweed-volume
      -ip.bind=0.0.0.0
      -dir=/data
    depends_on:
      - seaweed-master
    volumes:
      - seaweed-volume:/data
    ports:
      - "38080:8080"

  seaweed-filer:
    image: chrislusf/seaweedfs:latest
    command: >
      filer
      -master=seaweed-master:9333
      -ip=seaweed-filer
      -ip.bind=0.0.0.0
    depends_on:
      - seaweed-master
      - seaweed-volume
    ports:
      - "8888:8888"

  seaweed-s3:
    image: chrislusf/seaweedfs:latest
    command: >
      s3
      -filer=seaweed-filer:8888
      -ip.bind=0.0.0.0
    depends_on:
      - seaweed-filer
    ports:
      - "8333:8333"

volumes:
  seaweed-master:
  seaweed-volume: