workflow:
  name: build_deploy_application
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev"'
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
      when: always
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"'
      when: always

default:
  interruptible: true
  image: docker:24-cli

services:
  - docker:dind

stages:
  - lint
  - security
  - test
  - build
  - deploy

run_lint:
  image: oven/bun:1.3.10
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
      changes: 
        - src/**
      when: always
  retry: 2
  stage: lint
  before_script:
    - bun --version
  script:
    - bun biome ci --reporter=gitlab --colors=off > /tmp/code-quality.json
  after_script: echo "done."
  artifacts:
    name: artifacts
    reports:
      junit: $CI_PROJECT_DIR/test.xml
      sast: $CI_PROJECT_DIR/sast.xml
      codequality: $CI_PROJECT_DIR/code-quality.json
    paths:
      - $CI_PROJECT_DIR/test.xml
      - $CI_PROJECT_DIR/sast.xml
      - $CI_PROJECT_DIR/code-quality.json


gitleaks:
  stage: security
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks git --verbose --redact
  allow_failure: false



run_build:
  stage: build
  services:
    - name: docker:dind
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: always
  before_script:
    - docker version
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker buildx bake -f docker-bake.hcl default --push --set *.secrets="id=gh_token,env=GH_TOKEN"
  after_script:
    - echo "built && pushed"


run_deploy:
  image: ubuntu:devel
  stage: deploy
  retry: 2
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never
  variables:
    SERVICE_NAME: server-web
  before_script:
    - apt-get update -y && apt-get install -y openssh-client
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | ssh-add - > /dev/null
    - ssh-keyscan $HOST_IP > ~/.ssh/known_hosts
  script:
    - ssh $USERNAME@$HOST_IP "
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com &&
      docker-compose -f $COMPOSE_FILE down \"$SERVICE_NAME\" &&
      docker-compose -f $COMPOSE_FILE up -d
      "
  after_script:
    - echo "Application restarted."

