---
apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secret
  namespace: dbs
type: Opaque
stringData:
  pgsql-username: postgres
  pgsql-password: postgres
  pgadmin-email: postgres@gmail.com
  pgadmin-password: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: dbs
  labels:
    app: postgres
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      namespace: dbs
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-volume
          hostPath:
            path: /usr/backend/postgres
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: pgsql-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: pgsql-password
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dbs
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      namespace: dbs
      labels:
        app: pgadmin
    spec:
      automountServiceAccountToken: false
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:snapshot
          resources:
            requests:
              cpu: "0.2"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: pgadmin-email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: pgadmin-password
            - name: PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT
              value: "False"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: dbs
spec:
  type: LoadBalancer
  selector:
    app: pgsql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
# Service pgadmin
apiVersion: v1
kind: Service
metadata:
  namespace: dbs
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
