apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secret
  namespace: dbs
type: Opaque
data:
  pgsql-username: cG9zdGdyZXM= #postgres
  pgsql-password: cG9zdGdyZXM= #postgres
  pgadmin-email: dXNlckBnbWFpbC5jb20= #user@gmail.com
  pgadmin-password: cGdhZG1pbg== #pgaadmin
