apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secret
type: Opaque
data:
  pgsql-username: cG9zdGdyZXM=
  pgsql-password: cG9zdGdyZXM=
  pgadmin-email: dmljdG9yZXNwb2lyLmRldkBnbWFpbC5jb20=
  pgadmin-password: cGdhZG1pbg==
