# Deploy: pgsql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pgsql
  namespace: dbs
  labels:
    app: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      namespace: dbs
      labels:
        app: pgsql
    spec:
      volumes:
        - name: pgsql-volume
          hostPath:
            path: /var/lib/docker/volumes/pgsql-volume
      containers:
        - name: pgsql
          image: postgres:17-alpine
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pgsql-secret
                key: pgsql-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsql-secret
                key: pgsql-password
          - name: POSTGRES_DB
            value: postgres
          volumeMounts:
          - name: pgsql-volume
            mountPath: /var/lib/postgresql/data
---
# Svc pgsql
apiVersion: v1
kind: Service
metadata:
  name: service-pgsql
  namespace: dbs
spec:
  type: LoadBalancer
  selector:
    app: pgsql
  ports:
    - protocol:  TCP
      port: 5432
      targetPort: 5432

---
# Deploy: pgadmin
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dbs
  name: deploy-pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      namespace: dbs
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:snapshot
          ports:
          - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: pgadmin-email  
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: pgadmin-password  
            - name: PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT
              value: "True"
---
# Service pgadmin
apiVersion: v1
kind: Service
metadata:
  namespace: dbs
  name: service-pgadmin
spec:
  selector:
    app: pgadmin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80