# install loki plugin
# docker plugin install grafana/loki-docker-driver

networks:
  dockernet:
    external: true

volumes:
  loki_data:
    name: loki_data
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=127.0.0.1,rw"
      device: ":/mnt/data/loki"


services:
  grafana-loki:
    image: grafana/loki:main-3a68bc4
    restart: unless-stopped
    ports:
      - '30031:3100'
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
      - loki_data:/loki:rw
    networks:
      - dockernet
    labels:
      - traefik.enable=true
      - traefik.http.services.loki.loadbalancer.server.port=3100
      - traefik.http.routers.loki.entrypoints=http,https
      - traefik.http.routers.loki.rule=Host(`loki.<domain.com>`)
      - traefik.http.routers.loki.tls=true
      - traefik.http.routers.loki.tls.certresolver=letsencrypt