[mysqld]
bind-address = 0.0.0.0
max_connections = 200
innodb_buffer_pool_size = 512M
innodb_log_file_size = 128M
query_cache_limit = 1M
query_cache_size = 64M
slow_query_log = 1

# # for production
# ssl-ca = /etc/mysql/certs/ca-cert.pem
# ssl-cert = /etc/mysql/certs/server-cert.pem
# ssl-key = /etc/mysql/certs/server-key.pem
# require_secure_transport = ON