apiVersion: v1
kind: Pod
metadata:
  name: appname
  namespace: demo
spec:
  containers:
    - name: appname
      image: <Image:tag>
      ports:
        - containerPort: 0000
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
