apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-name
  labels:
    app: appname
spec:
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
