apiVersion: v1
kind: Service
metadata:
  name: appname-service
  namespace: namespace
selector:
  app: appname
# type: ClusterIP / NodePort / LoadBalancer
ports:
  - name: portname
    port: 8080
    targetPort: 8080
    # protocol: TPC / UDP