name: pgadmin

services:
  pgadmin:
    image: dpage/pgadmin4:snapshot
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: "512MiB"
        limits:
          cpus: "1.0"
          memory: "1024MiB"
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://localhost:80/pgadmin4/misc/ping" ]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 70s
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.host
      PGADMIN_DEFAULT_PASSWORD: Password123!
      PGADMIN_CONFIG_SERVER_MODE: True
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: False
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: True
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 60
      PGADMIN_CONFIG_MAX_CONNECTION_DURATION: 600
      PGADMIN_CONFIG_TIMEOUT: 600
      PGADMIN_LISTEN_PORT: 80
      GUNICORN_TIMEOUT: 600
      GUNICORN_THREADS: 4
      SCRIPT_NAME: /pgadmin4

      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
    networks:
      db-net:
      docker-net:
    labels:
      traefik.enable: true
      traefik.http.services.pgadmin-svc.loadbalancer.server.port: 80

      traefik.http.routers.pgadmin-rtr.entrypoints: websecure
      traefik.http.routers.pgadmin-rtr.rule: "Host(`pgadmin.localhost`) && PathPrefix(`/pgadmin4`)"
      traefik.http.routers.pgadmin-rtr.service: pgadmin-svc
      traefik.http.routers.pgadmin-rtr.tls: true
      traefik.http.routers.pgadmin-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.pgadmin-rtr.middlewares: pgadmin-redirect

      traefik.http.middlewares.pgadmin-reqheaders.headers.customrequestheaders.X-Script-Name: /pgadmin4
      traefik.http.middlewares.pgadmin-reqheaders.headers.customrequestheaders.X-Forwarded-Prefix: /pgadmin4


networks:
  docker-net:
    external: true
  db-net:
    external: true

volumes:
  pgadmin-vol:
    name: pgadmin-vol
    driver: local
