networks:
  dockernet:
    external: true
services:
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    restart: unless-stopped
    container_name: mongodb.db
    networks:
      - dockernet
    ports:
      - 27018:27017
    # volumes:
    #   - mongodb_data:/bitnami/mongodb
    environment:
      - MONGODB_ENABLE_JOURNAL=${MONGODB_ENABLE_JOURNAL:-false}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-no}
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER:-root-admin}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-root-password}
      - MONGODB_USERNAME=${MONGODB_USERNAME:-mongo}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-mongo}
  mongodb-express:
    image: mongo-express:1-20
    restart: unless-stopped
    networks:
      - dockernet
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=${ME_CONFIG_OPTIONS_EDITORTHEME:-ambiance}
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER:-mongodb}
      - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT:-27017}
      - ME_CONFIG_BASICAUTH=${ME_CONFIG_BASICAUTH:-false}
      - ME_CONFIG_SITE_COOKIESECRET=${ME_CONFIG_SITE_COOKIESECRET:-secret-key}
      - ME_CONFIG_SITE_SESSIONSECRET=${ME_CONFIG_SITE_SESSIONSECRET:-secret-key}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME:-user}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD:-}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${ME_CONFIG_MONGODB_AUTH_DATABASE:-}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${ME_CONFIG_MONGODB_AUTH_USERNAME:-}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${ME_CONFIG_MONGODB_AUTH_PASSWORD:-}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN:-true}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME:-mongo}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD:-mongo}
      - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT:-}
