networks:
  dockernet:
    external: true

services:
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    networks:
      - dockernet
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-admin-password}
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio-rtr.entrypoints=http,https
      - traefik.http.routers.minio-rtr.tls=true
      - traefik.http.routers.minio-rtr.tls.certresolver=dev-letsencrypt
      - traefik.http.routers.minio-rtr.rule=Host(`minio.local.kvruntime.com`)
      - traefik.http.services.minio-svc.loadbalancer.server.port=9000

# API: http://172.17.0.2:9000  http://127.0.0.1:9000
# WebUI: http://172.17.0.2:9001  http://127.0.0.1:9001