networks:
  dockernet:
    external: true

volumes:
  minio_storage:
    name: minio_storage

services:
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    networks:
      - dockernet
    ports:
      - 10000:9000 #api
      - 10001:9001 #webui
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-admin-password}
    volumes:
      - minio_storage:/data:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio-rtr.entrypoints=http,https
      - traefik.http.routers.minio-rtr.tls=true
      - traefik.http.routers.minio-rtr.tls.certresolver=dev-letsencrypt
      - traefik.http.routers.minio-rtr.rule=Host(`minio.local.kvruntime.com`)
      - traefik.http.services.minio-svc.loadbalancer.server.port=9000
