networks:
  dockernet:
    external: true

services:
  langflow:
    image: langflowai/langflow:v1.1.0 
    restart: unless-stopped
    networks:
      - dockernet
    ports:
      - 7860:7860
    environment:
      - LANGFLOW_AUTO_LOGIN=${LANGFLOW_AUTO_LOGIN:-False}
      - LANGFLOW_SUPERUSER=${LANGFLOW_SUPERUSER:-admin}
      - LANGFLOW_SUPERUSER_PASSWORD=${LANGFLOW_SUPERUSER_PASSWORD:-securepassword}
      - LANGFLOW_SECRET_KEY=${LANGFLOW_SECRET_KEY:-randomly_generated_secure_key}
      - LANGFLOW_NEW_USER_IS_ACTIVE=${LANGFLOW_NEW_USER_IS_ACTIVE:-False}
        