name: portainer

networks:
  dockernet:
    external: true

volumes:
  portainer-vol:
    name: portainer-vol
    driver: local
    # driver_opts:
    #   type: nfs4
    #   o: "addr=127.0.0.1,rw"
    #   device: ":/mnt/storage01/docker/portainer"

services:
  portainer:
    image: portainer/portainer-ce:sts
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 400Mib
          cpus: 0.4
    networks:
      - dockernet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-vol:/data:rw
    labels:
      - autoheal=true
      - traefik.enable=true
      - traefik.http.services.portainer-svc.loadbalancer.server.port=9000
      - traefik.http.routers.portainer-rtr.entrypoints=http,https
      - traefik.http.routers.portainer-rtr.rule=Host(`portainer.localhost`)
      - traefik.http.routers.portainer-rtr.tls=true
      - traefik.http.routers.portainer-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.portainer-rtr.service=portainer-svc
      # - traefik.http.routers.portainer-rtr.tls.middlewares=
