name: mimir

x-mimir: &mimir
  image: grafana/mimir:latest
  command:
    - -config.file=/etc/mimir.yaml
  expose:
    - 8080
    - 7946
    - 9095
  deploy:
    resources:
      limits:
        memory: 300Mib
        cpus: "0.3"
  networks:
    grafana-net:
  configs:
    - source: mimir_yaml
      target: /etc/mimir.yaml
  healthcheck:
    test:
      [
        "CMD",
        "wget",
        "-q",
        "-O-",
        "http://localhost:8080/ready"
      ]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  mimir-01:
    <<: *mimir
    hostname: mimir-01
  mimir-02:
    <<: *mimir
    hostname: mimir-02
  mimir-03:
    <<: *mimir
    hostname: mimir-03
  mimir-04:
    <<: *mimir
    hostname: mimir-04

  mimir:
    depends_on:
      mimir-01:
        condition: service_started
      mimir-02:
        condition: service_started
      mimir-03:
        condition: service_started
      mimir-04:
        condition: service_started
    image: caddy:2-alpine
    networks:
      docker-net:
      grafana-net:
    configs:
      - source: mimir_caddyfile
        target: /etc/caddy/Caddyfile
    labels:
      traefik.enable: true
      traefik.http.services.mimir-svc.loadbalancer.server.port: 80
      traefik.http.routers.mimir-rtr.rule: Host(`mimir.localhost`)
      traefik.http.routers.mimir-rtr.tls: true
      traefik.http.routers.mimir-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.mimir-rtr.service: mimir-svc

configs:
  mimir_caddyfile:
    file: "./configs/mimir.Caddyfile"
  mimir_yaml:
    file: "./configs/mimir.yaml"

networks:
  docker-net:
    external: true
  grafana-net:
    external: true
