name: mimir

x-mimir: &mimir
  image: grafana/mimir:3.2.0
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"
  command:
    - -config.file=/etc/mimir.yaml
    - -config.expand-env=true
  expose:
    - 8080
    - 7946
    - 9095
  deploy:
    resources:
      reservations:
        memory: "150MiB"
        cpus: "0.15"
      limits:
        memory: "300MiB"
        cpus: "0.3"
  networks:
    grafana-net:
  configs:
    - source: mimir_yaml
      target: /etc/mimir.yaml
  environment:
    MIMIR_S3_ENDPOINT: ${MIMIR_S3_ENDPOINT}
    MIMIR_S3_REGION: ${MIMIR_S3_REGION}
    MIMIR_S3_BUCKET: mimir
    MIMIR_S3_ACCESS_KEY: ${MIMIR_S3_ACCESS_KEY}
    MIMIR_S3_SECRET_KEY: ${MIMIR_S3_SECRET_KEY}

services:
  mimir-01:
    <<: *mimir
    hostname: mimir-01
  mimir-02:
    <<: *mimir
    hostname: mimir-02
  mimir-03:
    <<: *mimir
    hostname: mimir-03
  mimir-04:
    <<: *mimir
    hostname: mimir-04

  mimir:
    depends_on:
      mimir-01:
        condition: service_started
      mimir-02:
        condition: service_started
      mimir-03:
        condition: service_started
      mimir-04:
        condition: service_started
    image: caddy:2-alpine
    deploy:
      resources:
        reservations:
          memory: "128MiB"
          cpus: "0.25"
        limits:
          memory: "256MiB"
          cpus: "0.5"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      docker-net:
      grafana-net:
    configs:
      - source: mimir_caddyfile
        target: /etc/caddy/Caddyfile
    labels:
      traefik.enable: "true"
      traefik.http.services.mimir-svc.loadbalancer.server.port: 80
      traefik.http.routers.mimir-rtr.rule: Host(`mimir.localhost`)
      traefik.http.routers.mimir-rtr.tls: true
      traefik.http.routers.mimir-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.mimir-rtr.service: mimir-svc

configs:
  mimir_caddyfile:
    file: "./configs/mimir.Caddyfile"
  mimir_yaml:
    file: "./configs/mimir.yaml"

networks:
  docker-net:
    external: true
  grafana-net:
    external: true
