networks:
  docker-net:
    external: true

configs:
  caddy_file:
    file: ./Caddyfile

services:
  caddy:
    image: caddy:2-alpine
    networks:
      - docker-net
    ports:
      - 38080:80
    configs:
      - source: caddy_file
        target: /etc/caddy/Caddyfile
    # environment:
    #   OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://alloy:4318/v1/traces

  webapp-01:
    image: nginxdemos/hello:0.4
    networks:
      - docker-net
  webapp-02:
    image: nginxdemos/hello:0.4
    networks:
      - docker-net
  webapp-03:
    image: nginxdemos/hello:0.4
    networks:
      - docker-net