apiVersion: v1
kind: Pod
metadata:
  name: appname
  namespace: demo
spec:
  volumes:
    - name: nfs-volume
      nfs:
        path: "/path/to/nfs"
        server: "0.0.0.0"
        readOnly: false
    - name: hostpath-volume
      hostPath:
        type: DirectoryOrCreate
        path: "/path/to/dir"
  containers:
    - name: appname
      image: <Image:tag>
      ports:
        - containerPort: 0000
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
