apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-name
provisioner: no-provisioner # kubernetes.io/aws-ebs | example.com/external-nfs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstCustomer
parameters:
  type: gp2
  server: endpoint.end
  path: /path/to/share
  readOnly: "false"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
reclaimPolicy: Retain
provisioner: nfs-provisioner  # This is a placeholder; you may need to use a specific provisioner
volumeBindingMode: WaitForFirstCustomer
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"
