groups:
  - name: security-alerts
    interval: 1m

    rules:
      - alert: TooManySSHFailures

        expr: |
          sum(
            count_over_time(
              {service="auth"} |= "Failed password" [5m]
            )
          ) > 20

        for: 5m

        labels:
          severity: warning
          team: security

        annotations:
          summary: "High SSH failure rate"
          description: "More than 20 failed SSH logins in 5 minutes"