name: appname

services:
  service-name:
    image: <image>:<tag>
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 150Mb
          cpus: 0.1
        limits:
          memory: 200Mb
          cpus: 0.2
    networks:
      network-name:
    ports:
      - '<0000>:<0000>'
    configs:
      - source: app.conf
        target: /path/to/config.conf

    volumes:
      - volume-name:/path/to/data:rw
    environment:
      ENV_1: ${ENV_1}
      ENV_2: ${ENV_2}
    labels:
      traefik.enable: true
      traefik.http.services.appname-svc.loadbalancer.server.port: <0000>
      traefik.http.routers.appname-rtr.rule: Host(`<appname.domain.com>`)
      traefik.http.routers.appname-rtr.tls: true
      traefik.http.routers.appname-rtr.tls.certresolver: <certresolver>
      traefik.http.routers.appname-rtr.service: appname-svc

networks:
  network-name:
    external: true

configs:
  app.conf:
    content: |
      appname: elementor
      version: 1.0.0
      backend_url: http://localhost:9090
  config.yml:
    file: /path/to/file

volumes:
  volume-name:
    name: volume-name
    driver: local
    driver_opts:
      type: nfs
      device: :/path/to/volume
      o: 'addr=127.0.0.1,rw'