networks:
  dockernet:
    external: true

services:
  chromadb:
    image: chromadb/chroma:0.5.21.dev2
    ports:
      - 8000:8000
    networks:
      - dockernet
  chromadb-admin:
    image: fengzhichao/chromadb-admin
    ports:
      - 3000:3000
    networks:
      - dockernet
