networks:
  dockernet:
    external: true

secrets:
  db_user:
    file: db_user
  db_password:
    file: db_password
  root_password:
    file: root_password

services:
  mysql:
    image: mysql:8.0
    networks:
      - dockernet
    environment:
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root_password
    secrets:
      - db_user
      - db_password
      - root_password

  phpmyadmin:
    image: phpmyadmin:5-apache
    restart: unless-stopped
    cpus: 0.75
    mem_limit: 526Mb
    secrets:
      - db_user
      - db_password
    ports:
      - 9999:80
    networks:
      - dockernet
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/root_password
      - MYSQL_USER=/run/secrets/db_user
      - MYSQL_PASSWORD=/run/secrets/db_password
      - PMA_HOST=mysql
      - PMA_VERBOSE=true
      # - MYSQL_DATABASE=mysql
      # - PMA_ABSOLUTE_URI=
    labels:
      - traefik.enable=true
      - traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80