workflow:
  name: docker-in-docker-pipeline


# these variable used for dind when dealing with selfhost runner
# variables:
#   DOCKER_TLS_CERTDIR: ""
#   DOCKER_HOST: tcp://docker:2375
#   DOCKER_DRIVER: overlay2
#   DOCKER_BUILDKIT: 1


services:
  - name: docker:24-dind
    # enable when working with selfhost runner
    # alias: docker
    # command: ["--tls=false"]

default:
  interruptible: true
  image: ubuntu:devel
  # tags:
  #   - srv-prod
  #   - docker

run_build:
  stage: build
  image: docker:24
  tags:
    - srv
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: always
  before_script:
    - docker version
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker buildx bake -f docker-bake.hcl target-name --push --set *.secrets="id=gh_token,env=GH_TOKEN"
  after_script:
    - echo "built && pushed"
