workflow:
  name: scan-docker-assets-pipeline

variables:
  TRIVY_CACHE_DIR: ".trivycache/"
  TRIVY_NO_PROGRESS: "true"

scan_dockerfile:
  stage: build
  image:
    name: aquasec/trivy:latest
    entrypoint: [ "" ]
  script:
    - trivy config Dockerfile
    - trivy config --format json --output dockerfile-scan-report.json Dockerfile
  artifacts:
    when: always
    reports:
      container_scanning: dockerfile-scan-report.json
    paths:
      - dockerfile-scan-report.json
    expire_in: 1 week

scan_image:
  stage: scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [ "" ]
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always
  cache:
    paths:
      - .trivycache/
  before_script:
    - export TRIVY_USERNAME=$CI_REGISTRY_USER
    - export TRIVY_PASSWORD=$CI_REGISTRY_PASSWORD
  script:
    - trivy image --severity HIGH,CRITICAL $CI_REGISTRY_IMAGE:prod
    - trivy image --format template --template "@/contrib/gitlab.tpl" --output container-scanning-report.json $CI_REGISTRY_IMAGE:prod
  artifacts:
    reports:
      container_scanning: container-scanning-report.json
