networks:
  dockernet:
    external: true

volumes:
  minio_storage:
    name: minio_storage
    driver: local
    driver_opts:
      type: nfs4
      o: addr=0.0.0.0,rw,nolock,hard,nointr,nfsvers=4.1
      device: :/mnt/storage/minio

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    restart: unless-stopped
    command: server /data --console-address ":9001"
    networks:
      - dockernet
    ports:
      - 9000:9000 # api
      - 9001:9001 # webui
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL:-http://localhost:9000} # required only for reverse-proxy
    volumes:
      - minio_storage:/data:rw
    labels:
      - traefik.enable=true
        # services
      - traefik.http.services.minio.loadbalancer.server.port=9000
        # routes
      - traefik.http.routers.minio.entrypoints=http,https
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.certresolver=letsencrypt
      - traefik.http.routers.minio.rule=Host(`minio.<domain.com>`)
