networks:
  dockernet:
    external: true

services:
  traefik-proxy:
    image: traefik:v3.3
    restart: unless-stopped
    command:
      # Globals
      - --global.checknewversion=true
      - '--global.sendanonymoususage=false'
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--log.format=common' #common|json
      - '--accesslog.filepath=/var/lib/traefik/traefik.log'
      - '--accesslog.format=json'
        # entrypoints
      - '--entryPoints.http.address=:80'
      - '--entryPoints.https.address=:443'
      - '--entryPoints.http.http.redirections.entryPoint.to=https'
      - '--entryPoints.http.http.redirections.entryPoint.scheme=https'
        # Providers
      - '--providers.docker.endpoint=unix://var/run/docker.sock'
      - '--providers.docker.exposedbydefault=false'
        # http challenge
      - '--certificatesResolvers.letsencrypt.acme.email=user@domain.com'
      - '--certificatesResolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.letsencrypt.acme.storage=/var/traefik/certs/letsencrypt-acme.json'
      - '--certificatesResolvers.letsencrypt.acme.httpChallenge.entrypoint=http'
      # dns challenge
      - '--certificatesResolvers.cloudflare.acme.email=user@domain.com'
      - '--certificatesResolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.cloudflare.acme.storage=/var/traefik/certs/cloudflare-acme.json'
      - '--certificatesResolvers.cloudflare.acme.keyType=EC256'
      - '--certificatesResolvers.cloudflare.acme.dnsChallenge.provider=cloudflare'
      - '--certificatesResolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53'
    networks:
      - dockernet
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/certs:/var/traefik/certs:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    labels:
      - traefik.enable=true
      # - -- (services)
      - traefik.http.services.traefik-svc.loadbalancer.server.port=8080
      # - -- (routers)
      - traefik.http.routers.traefik-rtr.entrypoints=http,https
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.domain.com`)
      - traefik.http.routers.traefik-rtr.tls=true
      - traefik.http.routers.traefik-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-rtr.tls.domains[0].main=domain.com
      - traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.domain.com
# acme.caserver=https://acme-v02.api.letsencrypt.org/directory
# acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

