name: grafana-minio

networks:
  dockernet:
    external: true
  grafana-net:
    external:
      true

volumes:
  grafana-minio-vol:
    name: grafana-minio-vol
    driver: local
    # driver_opts:
    #   type: nfs4
    #   o: 'addr=127.0.0.1,rw'
    #   device: ':/mnt/storage/minio'

services:
  grafana-minio:
    image: minio/minio:latest
    restart: unless-stopped
    entrypoint: ''
    command:
      - sh
      - -c
      - mkdir -p /data/{grafana,mimir,loki,tempo} && minio server /data --address ":9000"
    networks:
      - grafana-net
    # ports:
    #   - 9000:9000 # api
    #   - 9001:9001 # console
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password}
    volumes:
      - grafana-minio-vol:/data:rw
