name: wordpress

networks:
  dockernet:
    external: true
  wordpress-net: {}

volumes:
  wordpress-db-vol:
    name: wordpress-db-vol
    driver: local
    # driver_opts:
    #   type: nfs4
    #   device: :/path/to/volume
    #   o: 'addr=127.0.0.1,rw'
  wordpress-web-vol:
    name: wordpress-web-vol
    driver: local
    # driver_opts:
    #   type: nfs4
    #   device: :/path/to/volume
    #   o: 'addr=127.0.0.1,rw'

services:
  wordpress-db:
    image: mysql:8.0
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 400Mb
          cpus: 0.2
    networks:
      - wordpress-net
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    volumes:
      - wordpress-db-vol:/var/lib/mysql

  wordpress-web:
    depends_on:
      - wordpress-db
    image: wordpress:6.8-apache
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 200Mb
          cpus: 0.2
    networks:
      - wordpress-net
      - dockernet
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - wordpress-web-vol:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.services.wordpress-svc.loadbalancer.server.port=80
      - traefik.http.routers.wordpress-rtr.entrypoints=http,https
      - traefik.http.routers.wordpress-rtr.rule=Host(`wordpress.localhost`)
      - traefik.http.routers.wordpress-rtr.tls=true
      - traefik.http.routers.wordpress-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.wordpress-rtr.service=wordpress-svc
      # - traefik.http.routers.wordpress-rtr.middlewares=

      - traefik.http.routers.wordpress-auth-rtr.entrypoints=http,https
      - traefik.http.routers.wordpress-auth-rtr.rule=Host(`wordpress.localhost`) && PathPrefix(`/wp-login`)
      - traefik.http.routers.wordpress-auth-rtr.tls=true
      - traefik.http.routers.wordpress-auth-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.wordpress-auth-rtr.service=wordpress-svc
      # - traefik.http.routers.wordpress-auth-rtr.middlewares=

      - traefik.http.routers.wordpress-admin-rtr.entrypoints=http,https
      - traefik.http.routers.wordpress-admin-rtr.rule=Host(`wordpress.localhost`) && PathPrefix(`/wp-admin`)
      - traefik.http.routers.wordpress-admin-rtr.tls=true
      - traefik.http.routers.wordpress-admin-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.wordpress-admin-rtr.service=wordpress-svc
      # - traefik.http.routers.wordpress-admin-rtr.middlewares=
