# Use seq for OpenTelemetry Logs
# https://datalust.co/seq
# data sending url : http://seq:port/ingest/oltp/v1/logs

networks:
  dockernet:
    external: true

services:
  seq:
    image: datalust/seq:2024
    restart: unless-stopped
    networks:
      - dockernet
    ports:
      - 30080:80 
      - 5341:5341 
    environment:
      # - PH=
      - ACCEPT_EULA=Y
      # - SEQ_API_CANONICALURI=https://seq.example.com
      # - SEQ_FIRSTRUN_ADMINPASSWORDHASH="$PH"
    # volumes: 
    #   - seq_storage:/data
  