name: n8n

networks:
  dockernet:
    external: true
  n8n-net: {}

volumes:
  n8n-web-vol:
    name: n8n-web-vol
    driver: local
    # driver_opts:
    #   type: nfs
    #   device: :/path/to/volume
    #   o: 'addr=127.0.0.1,rw'
  n8n-db-vol:
    name: n8n-db-vol
    driver: local
    # driver_opts:
    #   type: nfs
    #   device: :/path/to/volume
    #   o: 'addr=127.0.0.1,rw'
  n8n-minio-vol:
    name: n8n-minio-vol
    driver: local
    # driver_opts:
    #   type: nfs
    #   device: :/path/to/volume
    #   o: 'addr=127.0.0.1,rw'


services:
  n8n-minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    entrypoint: ''
    command:
      - sh
      - -c
      - mkdir -p /data/n8n && minio server /data --address ":9000"
    networks:
      - n8n-net
    deploy:
      resources:
        limits:
          memory: 300Mb
          cpus: 0.3
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    volumes:
      - n8n-minio-vol:/data:rw
  n8n-db:
    image: postgres:17-alpine
    restart: unless-stopped
    networks:
      - n8n-net
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - n8n-db-vol:/var/lib/postgresql/data
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-web:
    depends_on:
      n8n-db:
        condition: service_healthy
    image: n8nio/n8n:next
    restart: unless-stopped
    networks:
      - dockernet
      - n8n-net
    # ports:
    #   - "127.0.0.1:5678:5678"
    volumes:
      # - n8n-web-vol:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./n8n/shared:/data/shared
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST
      - DB_POSTGRESDB_USER
      - DB_POSTGRESDB_PASSWORD
      - DB_POSTGRESDB_DATABASE
      
      - N8N_EDITOR_BASE_URL
      - N8N_PREVIEW_MODE=true
      - N8N_TEMPLATES_ENABLED=true
      - N8N_DIAGNOSTICS_ENABLED=true
      - N8N_PERSONALIZATION_ENABLED=true
      - N8N_ENCRYPTION_KEY
      - N8N_USER_MANAGEMENT_JWT_SECRET
      - WEBHOOK_URL
      - N8N_PUBLIC_API_ENDPOINT
      - N8N_REINSTALL_MISSING_PACKAGES=true
      
      - N8N_EXTERNAL_STORAGE_S3_HOST
      - N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME
      - N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY
      - N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET
      - N8N_EXTERNAL_STORAGE_S3_AUTH_AUTO_DETECT
      
      - N8N_METRICS=true
      - N8N_METRICS_INCLUDE_CACHE_METRICS=true
      - N8N_METRICS_INCLUDE_MESSAGE_EVENT_BUS_METRICS=true
      - N8N_METRICS_INCLUDE_WORKFLOW_ID_LABEL=true
      - N8N_METRICS_INCLUDE_NODE_TYPE_LABEL=true
      - N8N_METRICS_INCLUDE_CREDENTIAL_TYPE_LABEL=true
      - N8N_METRICS_INCLUDE_API_ENDPOINTS=true
      - N8N_METRICS_INCLUDE_API_PATH_LABEL=true
      - N8N_METRICS_INCLUDE_API_METHOD_LABEL=true
      - N8N_METRICS_INCLUDE_API_STATUS_CODE_LABEL=true
      - N8N_METRICS_INCLUDE_QUEUE_METRICS=true
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - N8N_PUBLIC_API_DISABLED=false
      - N8N_PUBLIC_API_SWAGGERUI_DISABLED=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # - LOGS
      - N8N_LOG_LEVEL=info
      - N8N_LOG_FORMAT=json
      
      - GENERIC_TIMEZONE=UTC
      - N8N_DEFAULT_LOCALE=en
      
      - N8N_SMTP_HOST
      - N8N_SMTP_PORT
      - N8N_SMTP_USER
      - N8N_SMTP_PASS
      - N8N_SMTP_SENDER
      
    labels:
      - traefik.enable=true
      
      - traefik.http.services.n8n-svc.loadbalancer.server.port=5678
      - traefik.http.routers.n8n-rtr.entrypoints=http,https
      - traefik.http.routers.n8n-rtr.rule=Host(`n8n.localhost`)
      - traefik.http.routers.n8n-rtr.tls=true
      - traefik.http.routers.n8n-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.n8n-rtr.service=n8n-svc
      # - traefik.http.routers.n8n-rtr.middlewares=
