name: ansible

secrets:
  automation_key:
    file: ${HOME}/.ssh/automation_key
  
configs:  
  entrypoint_sh:
    content: |
      #!/bin/sh 
      mkdir -p /root/.ssh
      cat /run/secrets/automation_key | tr -d '\015' > /root/.ssh/automation_key
      echo "" >> /root/.ssh/automation_key
      chmod 600 /root/.ssh/automation_key
      exec tail -f /dev/null

services:
  ansible:
    image: ansible:dev
    working_dir: /ansible
    entrypoint: 
      - /bin/sh 
    command:
      - /entrypoint.sh
    secrets:
      - automation_key
    configs:
      - source: entrypoint_sh
        target: /entrypoint.sh
    environment:
      ANSIBLE_HOST_KEY_CHECKING: false
      ANSIBLE_PRIVATE_KEY_FILE: /root/.ssh/automation_key
      ANSIBLE_PYTHON_INTERPRETER: auto
    volumes:
      - ./config/:/ansible:rw