volumes:
  open_webui_data:
    name: open_webui_data

networks:
  dockernet:
    external: true

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - dockernet
    ports:
      - 3000:8080
    volumes:
      - open_webui_data:/app/backend/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Ollama
      - OLLAMA_BASE_URL=http://ollama:11434
      - USE_OLLAMA_DOCKER=true
      - ENABLE_OLLAMA_API=true
      - ENABLE_IMAGE_GENERATION=True
      - AUTOMATIC1111_BASE_URL=http://host.docker.internal:7860/
      # - CORS_ALLOW_ORIGIN=*

      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL="http://searxng:8080/search?q=<query>"
      # Auth
      - WEBUI_AUTH=false
      - WEBUI_NAME
      - CUSTOM_NAME=LocalStack

  # searxng:
  #   image: searxng/searxng:2024.9.12-c45870dd7
  #   container_name: searxng
  #   networks:
  #     - dockernet
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - ./searxng:/etc/searxng
    # restart: always
