# docker run -i -t --rm ghcr.io/tinyauthapp/tinyauth:nightly user create --interactive

name: tinyauth

services:
  tinyauth:
    image: ghcr.io/tinyauthapp/tinyauth:nightly
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    networks:
      docker-net:
    deploy:
      resources:
        reservations:
          memory: "250MiB"
          cpus: "0.25"
        limits:
          memory: "500MiB"
          cpus: "0.5"
    environment:
      TINYAUTH_APPURL: https://tinyauth.localhost
      TINYAUTH_LOG_JSON: true
      TINYAUTH_LOG_STREAMS_AUDIT_ENABLED: true
      TINYAUTH_AUTH_SECURECOOKIE: true
      TINYAUTH_UI_TITLE: tinyauth-app
      # TINYAUTH_UI_FORGOTPASSWORDMESSAGE: 

      # TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_NAME: Keycloak
      # TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_CLIENTID: tinyauth
      # TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_CLIENTSECRET: xxxxxxxxxxxxxx
      # TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_REDIRECTURL: https://tinyauth.localhost/api/oauth/callback/keycloak
      # TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_AUTHURL: https://keycloak.localhost/realms/therealm/protocol/openid-connect/auth
      # TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_TOKENURL: https://keycloak.localhost/realms/therealm/protocol/openid-connect/token
      # TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_USERINFOURL: https://keycloak.localhost/realms/therealm/protocol/openid-connect/userinfo
      # TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_SCOPES: openid profile email groups

      # TINYAUTH_OAUTH_PROVIDERS_AUTHENTIK_NAME: authentik
      # TINYAUTH_OAUTH_PROVIDERS_AUTHENTIK_CLIENTID: xxxxxxxxxxxxxxxxxxxxxxxx
      # TINYAUTH_OAUTH_PROVIDERS_AUTHENTIK_CLIENTSECRET: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      # TINYAUTH_OAUTH_PROVIDERS_AUTHENTIK_REDIRECTURL: https://tinyauth.localhost/api/oauth/callback/authentik
      # TINYAUTH_OAUTH_PROVIDERS_AUTHENTIK_AUTHURL: https://authentik.localhost/application/o/authorize/
      # TINYAUTH_OAUTH_PROVIDERS_AUTHENTIK_TOKENURL: http://authentik-server:9000/application/o/token/
      # TINYAUTH_OAUTH_PROVIDERS_AUTHENTIK_USERINFOURL: http://authentik-server:9000/application/o/userinfo/
      # TINYAUTH_OAUTH_PROVIDERS_AUTHENTIK_SCOPES: openid profile email groups

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tinyauth-vol:/data:rw
      - ./resources/background.png:/resources/background.png:ro
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.tinyauth-mdl.forwardauth.address: http://tinyauth:3000/api/auth/traefik
      traefik.http.services.tinyauth-svc.loadbalancer.server.port: 3000
      traefik.http.routers.tinyauth-rtr.entrypoints: websecure
      traefik.http.routers.tinyauth-rtr.rule: Host(`tinyauth.localhost`)
      traefik.http.routers.tinyauth-rtr.tls: true
      traefik.http.routers.tinyauth-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.tinyauth-rtr.service: tinyauth-svc
      # traefik.http.routers.traefik-rtr.middlewares=tinyauth-mdl
      # tinyauth.apps.myapp.config.domain: myapp.example.com
      # tinyauth.apps.myapp.ldap.groups: admins,monitoring
      # tinyauth.apps.myapp.oauth.groups: admins,monitoring



networks:
  docker-net:
    external: true

volumes:
  tinyauth-vol:
    name: tinyauth-vol
