name: mailpit

services:
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    networks:
      docker-net:
    expose:
      - 8025 #ui
      - 1025 #smpt
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "200MiB"

    environment:
      MP_ENABLE_PROMETHEUS: true
    labels:
      traefik.enable: true
      traefik.http.services.mailpit-svc.loadbalancer.server.port: 8025
      traefik.http.routers.mailpit-rtr.entrypoints: web,websecure
      traefik.http.routers.mailpit-rtr.rule: Host(`mailpit.localhost`)
      traefik.http.routers.mailpit-rtr.tls: true
      traefik.http.routers.mailpit-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.mailpit-rtr.service: mailpit-svc

networks:
  docker-net:
    external: true
