networks:
  dockernet:
    external: true

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  root_password:
    file: ./secrets/root_password

volumes:
  wordpress_db_storage:
    name: wordpress_db_storage
  wordpress_web_storage:
    name: wordpress_web_storage

services:
  wordpress_web:
    image: wordpress:6.7-apache
    restart: unless-stopped
    ports:
      - 30080:80
    networks:
      - dockernet
    environment:
      - WORDPRESS_DB_HOST=wordpress_db
      - WORDPRESS_DB_USER_FILE=/run/secrets/db_user
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
      - WORDPRESS_DB_NAME=db
    secrets:
      - db_user
      - db_password
    depends_on:
      - wordpress_db
    volumes:
      - wordpress_web_storage:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress-rtr.entrypoints=http,https
      - traefik.http.routers.wordpress-rtr.rule=Host(`${APP_URL}`)
      - traefik.http.routers.wordpress-rtr.tls=true
      - traefik.http.routers.wordpress-rtr.tls.certresolver=letsencrypt
      - traefik.http.services.wordpress-svc.loadbalancer.server.port=80

  wordpress_db:
    image: mysql:8.0
    cpus: 0.5
    mem_limit: "528Mib"
    restart: unless-stopped
    networks:
      - dockernet
    secrets:
      - root_password
      - db_user
      - db_password
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root_password
    volumes:
      - wordpress_db_storage:/var/lib/mysql
# system_admin YZt)Xu$GGcyN2RgtBy
