networks:
  dockernet:
    external: true

volumes:
  meilisearch:
  data:

services:
  hoarder-web:
    image: ghcr.io/hoarder-app/hoarder:0.10.0 #release
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 9990:3000
    env_file:
      - .env
    environment:
      - MEILI_ADDR=${MEILI_ADDR:-http://hoarder-meilisearch:7700}
      - BROWSER_WEB_URL=${BROWSER_WEB_URL:-http://hoarder-chrome:9222}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-fsdfdsfs}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-fsdfdsfs}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:9990}
      - DATA_DIR=/data
  hoarder-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  hoarder-meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: 'true'
    volumes:
      - meilisearch:/meili_data


