server:
  http_listen_port: 4040
  log_level: warn

storage:
  backend: filesystem
  filesystem:
    dir: /data/pyroscope
  # backend: s3
  # s3:
  #   bucket_name: pyroscope
  #   endpoint: minio:9000
  #   insecure: true
  #   access_key_id: admin
  #   secret_access_key: password
  #   s3forcepathstyle: true

limits:
  max_profile_size_bytes: 52428800
  max_label_name_length: 1024
  max_label_value_length: 2048
  ingestion_rate_mb: 50
  ingestion_burst_size_mb: 100

compaction:
  enabled: true

retention:
  max_age: 168h


