networks:
  dockernet:
    external: true

volumes:
  uptime_kuma_storage:
    name: uptime_kuma_storage

services:
  updtime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - uptime_kuma_storage:/app/data
