name: alloy-srv

networks:
  docker-net:
    external: true
  grafana-net:
    external: true


configs:
  all_server_alloy:
    file: "./configs/server-all.alloy"


volumes:
  alloy-vol:
    name: alloy-vol

services:
  alloy-srv:
    image:  grafana/alloy:latest
    hostname: alloy-srv
    expose:
      - 9090 #prometheus
      - 3100 #loki
      - 4317 #otlp-gprc
      - 4318 #otlp-http
    command: |
      run 
      --server.http.listen-addr=0.0.0.0:12345
      --stability.level=public-preview
      --storage.path=/var/lib/alloy/data
      /etc/alloy/all.alloy
    networks:
      - docker-net
      - grafana-net
    environment:
      - HOSTNAME=alloy-srv
    configs:
      - source: all_server_alloy
        target: /etc/alloy/all.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true

      traefik.http.services.alloy-srv-ui-svc.loadbalancer.server.port: 12345
      traefik.http.routers.alloy-srv-ui-rtr.entrypoints: web,websecure
      traefik.http.routers.alloy-srv-ui-rtr.rule: Host(`alloy-srv-ui.localhost`)
      traefik.http.routers.alloy-srv-ui-rtr.tls: true
      traefik.http.routers.alloy-srv-ui-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.alloy-srv-ui-rtr.service: alloy-srv-ui-svc

      traefik.http.services.alloy-srv-loki-svc.loadbalancer.server.port: 3100
      traefik.http.routers.alloy-srv-loki-rtr.entrypoints: web,websecure
      traefik.http.routers.alloy-srv-loki-rtr.rule: Host(`alloy-srv-loki.localhost`)
      traefik.http.routers.alloy-srv-loki-rtr.tls: true
      traefik.http.routers.alloy-srv-loki-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.alloy-srv-loki-rtr.service: alloy-srv-loki-svc

      traefik.http.services.alloy-srv-prom-svc.loadbalancer.server.port: 9090
      traefik.http.routers.alloy-srv-prom-rtr.entrypoints: web,websecure
      traefik.http.routers.alloy-srv-prom-rtr.rule: Host(`alloy-srv-prom.localhost`)
      traefik.http.routers.alloy-srv-prom-rtr.tls: true
      traefik.http.routers.alloy-srv-prom-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.alloy-srv-prom-rtr.service: alloy-srv-prom-svc

      traefik.http.services.alloy-srv-otlp-http-svc.loadbalancer.server.port: 4318
      traefik.http.routers.alloy-srv-otlp-http-rtr.entrypoints: web,websecure
      traefik.http.routers.alloy-srv-otlp-http-rtr.rule: Host(`alloy-srv-oltp.localhost`)
      traefik.http.routers.alloy-srv-otlp-http-rtr.tls: true
      traefik.http.routers.alloy-srv-otlp-http-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.alloy-srv-otlp-http-rtr.service: alloy-srv-otlp-http-svc
