# reset password: npm run reset-password
name: uptimekuma

services:
  uptimekuma-db:
    image: mariadb:12.0-rc
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: "200MiB"
          cpus: "0.25"
        limits:
          memory: "400MiB"
          cpus: "0.5"
    networks:
      uptimekuma-net:
    secrets:
      - password
      - root_password
    environment:
      MARIADB_USER: mariadb
      MARIADB_DATABASE: uptimekuma
      MARIADB_PASSWORD_FILE: "/run/secrets/password"
      MARIADB_ROOT_PASSWORD_FILE: "/run/secrets/root_password"
    volumes:
      - uptimekuma-db-vol:/var/lib/mysql

  uptimekuma-web:
    depends_on:
      uptimekuma-db:
        condition: service_started
    image: louislam/uptime-kuma:nightly2
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    networks:
      uptimekuma-net:
      docker-net:
    deploy:
      resources:
        reservations:
          memory: "200MiB"
          cpus: "0.25"
        limits:
          memory: "400MiB"
          cpus: "0.5"
    volumes:
      - uptimekuma-web-vol:/app/data
    labels:
      traefik.enable: "true"
      traefik.http.services.uptimekuma-svc.loadbalancer.server.port: 3001
      traefik.http.routers.uptimekuma-rtr.entrypoints: web,websecure
      traefik.http.routers.uptimekuma-rtr.tls: true
      traefik.http.routers.uptimekuma-rtr.tls.certresolver: letsencrypt
      traefik.http.routers.uptimekuma-rtr.rule: Host(`uptimekuma.localhost`)
      traefik.http.routers.uptimekuma-rtr.service: uptimekuma-svc

secrets:
  password:
    file: "./secrets/password"
  root_password:
    file: "./secrets/root_password"

networks:
  docker-net:
    external: true
  uptimekuma-net: {}

volumes:
  uptimekuma-db-vol:
    name: uptimekuma-db-vol
    driver: local

  uptimekuma-web-vol:
    name: uptimekuma-web-vol
    driver: local
