networks:
  dockernet:
    external: true

configs:
  grafana.conf:
    content: |
      # nginx.config
      events {
          worker_connections 1024;
      }
      http {
          upstream backend {
              server grafana-01:3000 max_fails=1 fail_timeout=1s;
              server grafana-02:3000 max_fails=1 fail_timeout=1s;
              server grafana-03:3000 max_fails=1 fail_timeout=1s backup;
          }
          server {
              listen 3000;
              access_log /dev/null;
              location / {
                  proxy_pass http://backend;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
                  proxy_set_header Host $$http_host;
              }
          }
      }

volumes:
  grafana-vol:
    name: grafana-vol

services:
  grafana:
    image: nginx:alpine
    expose:
      - 3000
    ports:
      - 33000:3000
    networks:
      - dockernet
    configs:
      - source: grafana.conf
        target: /etc/nginx/nginx.conf
        mode: 0
        uid: '0'
        gid: '0'
    depends_on:
      - grafana-01
      - grafana-02
      - grafana-03
    labels:
      - alloy.logs.enable=true
      - alloy.metrics.enable=true
      - alloy.traces.enable=true

      - traefik.enable=true
      - traefik.http.routers.grafana-rtr.entrypoints=http,https
      - traefik.http.routers.grafana-rtr.rule=Host(`grafana.<domain.com>`)
      - traefik.http.routers.grafana-rtr.tls=true
      - traefik.http.routers.grafana-rtr.tls.certresolver=letsencrypt
      - traefik.http.services.grafana-svc.loadbalancer.server.port=3000
  grafana-01:
    image: grafana/grafana-enterprise:main
    networks:
      - dockernet
    environment:
      - GF_LOG_LEVEL=${GF_LOG_LEVEL:-debug}
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED:-false}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-http://grafana:3000}
      - GF_USERS_DEFAULT_THEME=${GF_USERS_DEFAULT_THEME:-light}
    volumes:
      - grafana-vol:/var/lib/grafana:rw
    labels:
      - alloy.logs.enable=true
      - alloy.metrics.enable=true
      - alloy.traces.enable=true

  grafana-02:
    image: grafana/grafana-enterprise:main
    networks:
      - dockernet
    environment:
      - GF_LOG_LEVEL=${GF_LOG_LEVEL:-debug}
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED:-false}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-http://grafana:3000}
      - GF_USERS_DEFAULT_THEME=${GF_USERS_DEFAULT_THEME:-light}
    volumes:
      - grafana-vol:/var/lib/grafana:rw
    labels:
      - alloy.logs.enable=true
      - alloy.traces.enable=true
      - alloy.metrics.enable=true

  grafana-03:
    image: grafana/grafana-enterprise:main
    networks:
      - dockernet
    environment:
      - GF_LOG_LEVEL=${GF_LOG_LEVEL:-debug}
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED:-false}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-http://grafana:3000}
      - GF_USERS_DEFAULT_THEME=${GF_USERS_DEFAULT_THEME:-light}
    volumes:
      - grafana-vol:/var/lib/grafana:rw
    labels:
      - alloy.logs.enable=true
      - alloy.metrics.enable=true
      - alloy.traces.enable=true
