networks:
  dockernet:
    external: true

volumes:
  qdrant_storage:
    name: qdrant_storage

services:
  qdrant:
    image: qdrant/qdrant:master
    container_name: qdrant
    networks:
      - dockernet
    restart: unless-stopped
    environment:
      - RUN_MODE=production # development
    ports:
      - 6333:6333
      # - 6334:6334 # GRPC endpoint
    volumes:
      - qdrant_storage:/qdrant/storage
